### ISSUE TITLE
ラズパイのdocker環境でapiでのデータベースへのpostが失敗する

### ISSUE THREAD

**Issue by kmchord9** [kmchord9/django-api-server#2]
python post-test.py 
Traceback (most recent call last):
  File "post-test.py", line 30, in <module>
    with urllib.request.urlopen(request) as response:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by kmchord9** [comment]
HTTP Error 403: Forbidden
「このページ (HTTP エラー 403-アクセスは許可されていません) を表示する権限がありません」
権限がないのでエラーが出ている

**Comment by kmchord9** [comment]
django-rest-frameworkの権限設定

https://www.django-rest-framework.org/api-guide/authentication/
https://www.django-rest-framework.org/api-guide/permissions/

**Comment by kmchord9** [comment]
パスワードのtypoだった
